// Code generated by Kitex v0.0.5. DO NOT EDIT.

package grpcconfig

import (
	"github.com/cloudwego/kitex/server"
	"github.com/ldongpo/gconfig-client/kitex_gen/grpcConfig"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler grpcConfig.GrpcConfig, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
